var OptimizationConstants = {
  ALL_OPTIMIZATIONS_RECEIVED: 'ALL_OPTIMIZATIONS_RECEIVED',
  OPTIMIZATION_RECEIVED: 'OPTIMIZATION_RECEIVED',
  OPTIMIZATION_DELETED: 'OPTIMIZATION_DELETED',
};

module.exports = OptimizationConstants;
