var OptimizationConstants = {
  ALL_OPTIMIZATIONS_RECEIVED: 'ALL_OPTIMIZATIONS_RECEIVED',
  OPTIMIZATION_RECEIVED: 'OPTIMIZATION_RECEIVED',
  OPTIMIZATION_DELETED: 'OPTIMIZATION_DELETED',
  SEARCH_PARAM_RECEIVED: 'SEARCH_PARAM_RECEIVED',
};

module.exports = OptimizationConstants;
